### ISSUE TITLE
Playable Piano

### ISSUE THREAD

**Issue by Davinais** [sammer1107/WP2018_C#1]
Playable Piano on Home Page

**Comment by sammer1107** [comment]
Maybe usable sounds:
- [All 88 Piano Keys Every Piano Note with Diagram Sound Effect Free High Quality Sound FX](https://www.youtube.com/watch?v=dHb8R5gDvgM)
- [Piano Keys from Uncle Dave's Sound's](https://freesound.org/search/?a_tag=&a_username=&g=1&f=grouping_pack%3A%2210684_Uncle+Dave%27s+Sound%27s%22+&a_filename=&a_soundid=&q=c4+piano&s=%22score+desc%22&a_packname=&a_description=&advanced=&page=1#sound)
- [Piano Keys from piano notes](https://freesound.org/search/?q=piano%20c4&f=grouping_pack:%2218912_piano%20notes%22%20&s=%22score%20desc%22&g=1&advanced=0&a_tag=&a_filename=&a_description=&a_packname=&a_soundid=&a_username=)
- [Piano Keys from Upright piano multisamples](https://freesound.org/search/?a_tag=&a_username=&g=1&f=grouping_pack%3A%2217088_Upright+piano+multisamples%22+&a_filename=&a_soundid=&q=piano+c4&s=%22score+desc%22&a_packname=&a_description=&advanced=0&page=1#sound)

**Comment by Davinais** [comment]
Reference: [HTML5 JavaScript Piano](https://mrcoles.com/piano/)

**Comment by Davinais** [comment]
Solution Now:
Using [AudioSynth by keithwhor](https://github.com/keithwhor/audiosynth)
