### ISSUE TITLE
Movable character in the middle of the screen

### ISSUE THREAD

**Issue by sammer1107** [sammer1107/WP2018_C#11]
keep the character in the center of the screen while it moves around the map,
basic character design is need or just use anything to substitute

**Comment by sammer1107** [comment]
update c055b93e578bb279e4fcc86a2643f5694b8eb977 :
I'm now using WASD control, but will likely switch to mouse control

**Comment by Davinais** [comment]
I think we can preserve both control method.
Also, you don't need comment at "use strict"

**Comment by sammer1107** [comment]
The way of stopping the character when it reaches the destination should be modified, one possible solution maybe using tween

**Comment by sammer1107** [comment]
我感覺可以把操控方式改成只要滑鼠按著就會一直前進，放開之後就會只走到最後放開的位子。

**Comment by Davinais** [comment]
我自己是覺得可能還要做個尋路系統出來
