### ISSUE TITLE
Design a song for piano play along

### ISSUE THREAD

**Issue by sammer1107** [sammer1107/WP2018_C#6]
use javascript to indicate which key to play and,  when the player complete the short song. 
Slide the page down to project intro.

**Comment by Davinais** [comment]
I would implement a function that can indicate users which note to play by using 'Note Name' first.

Then we can handle the indicator easily.

**Comment by Davinais** [comment]
Implemented: See ccd930e087820c8a1a7fa14e2afa1b3e3704411d

Now I choose Option 2 for indication:
![Indication Options](https://user-images.githubusercontent.com/5267712/47608718-9408f580-da64-11e8-9baa-f3ebd78f289d.png)

**Comment by Davinais** [comment]
927ee6a73b40eec0c7bbb805a97788627592cc09
Using Scrollify to complete.
Now I temporarily choose "Oh Susanna" in D Major for indicating.

**Comment by sammer1107** [comment]
Nice
But we still need to maybe replay the song in original tempo again and say something like "Goodjob You just played Oh Susanna !" before scrolling to the next page so that the player know what he's actually doing

**Comment by Davinais** [comment]
a00b86a218d7d9edfa9024a6515a43fe01093b04
Has Implemented the notePlay function, now we can play song in original tempo easily.

What left is the feedback after the song played. Actually I'm quite not sure what to do.
